package main

import (
	"fmt"
	"github.com/KleinSamuel/gtamap/src/core/datastructure"
	"github.com/sirupsen/logrus"
	"math/rand"
	"time"
)

func generateCombinations(chars []rune, prefix string, length int, words *[]string) {
	if length == 0 {
		*words = append(*words, prefix+"1")
		//return
	}

	for _, char := range chars {
		generateCombinations(chars, prefix+string(char), length-1, words)
	}
}

type Test struct {
	Active int
	Root   int
}

func createString() {
	rand.Seed(time.Now().UnixNano())
	length := 2000
	chars := []rune{'A', 'C', 'T', 'G'}
	randomString := make([]rune, length)

	for i := range randomString {
		randomString[i] = chars[rand.Intn(len(chars))]
	}

	fmt.Println(string(randomString))
}

func main() {

	logrus.SetFormatter(&logrus.TextFormatter{
		FullTimestamp: true,
	})
	logrus.SetLevel(logrus.DebugLevel)

	//alphabet := []rune{'A', 'T', 'G', 'C'}
	//
	//for _, char := range alphabet {
	//	fmt.Println(char)
	//}
	//
	//var b byte = 255
	//var r rune = 2562222
	//
	//fmt.Println(b)
	//fmt.Println(r)
	//
	//os.Exit(1)

	//for i := 1; i <= 10; i++ {
	//	words := make([]string, 0)
	//	generateCombinations(alphabet, "", i, &words)
	//
	//	for _, word := range words {
	//
	//		fmt.Println("checking word", word)
	//
	//		tree := datastructure.CreateTree()
	//		tree.AddSequence(word, 0)
	//	}
	//}
	//fmt.Println("OK")

	//words := []string{"ABC", "DEF", "GHI", "JKL", "MNO", "PQR", "ABC"}
	//words := []string{"ABC1", "DEF2", "GHI3", "JKL4", "MNO5", "PQR6", "ABC7"}
	words := []string{"ABC", "CEF", "CEG", "CEH"}
	//words := []string{"ABCD", "ADEF", "ABCF", "ABKU"}
	//words := []string{"ABC1", "DEF2", "ABC3"}
	//words := []string{"ATGC1", "ATGG2", "ATTTTG13"}
	//words := []string{"AATAT1"}
	//words := []string{"AATATAT1"}
	//words := []string{"ATGCGC1"}
	//words := []string{"ATGACACCCACAGACTTCACAAG1"}
	//words := []string{"ATGACACCCACAGACTTCACAAGCCCTATTCCTAACATGGCTGATGAC1"}
	//words := []string{"ATGACACCCACAGACTTCACAAGCCCTATTCCTAACATGGCTGATGACTATGGCTCTGAATCCACATCTTCCATGGAAGACTACGTTAACTTCAACTTCACTGACTTCTACTGTGAGAAAAACAATGTCAGGCAGTTTGCGAGCCATTTCCTCCCACCCTTGTACTGGCTCGTGTTCATCGTGGGTGCCTTGGGCAACAGTCTTGTTATCCTTGTCTACTGGTACTGCACAAGAGTGAAGACCATGACCGACATGTTCCTTTTGAATTTGGCAATTGCTGACCTCCTCTTTCTTGTCACTCTTCCCTTCTGGGCCATTGCTGCTGCTGACCAGTGGAAGTTCCAGACCTTCATGTGCAAGGTGGTCAACAGCATGTACAAGATGAACTTCTACAGCTGTGTGTTGCTGATCATGTGCATCAGCGTGGACAGGTACATTGCCATTGCCCAGGCCATGAGAGCACATACTTGGAGGGAGAAAAGGCTTTTGTACAGCAAAATGGTTTGCTTTACCATCTGGGTATTGGCAGCTGCTCTCTGCATCCCAGAAATCTTATACAGCCAAATCAAGGAGGAATCCGGCATTGCTATCTGCACCATGGTTTACCCTAGCGATGAGAGCACCAAACTGAAGTCAGCTGTCTTGACCCTGAAGGTCATTCTGGGGTTCTTCCTTCCCTTCGTGGTCATGGCTTGCTGCTATACCATCATCATTCACACCCTGATACAAGCCAAGAAGTCTTCCAAGCACAAAGCCCTAAAAGTGACCATCACTGTCCTGACCGTCTTTGTCTTGTCTCAGTTTCCCTACAACTGCATTTTGTTGGTGCAGACCATTGACGCCTATGCCATGTTCATCTCCAACTGTGCCGTTTCCACCAACATTGACATCTGCTTCCAGGTCACCCAGACCATCGCCTTCTTCCACAGTTGCCTGAACCCTGTTCTCTATGTTTTTGTGGGTGAGAGATTCCGCCGGGATCTCGTGAAAACCCTGAAGAACTTGGGTTGCATCAGCCAGGCCCAGTGGGTTTCATTTACAAGGAGAGAGGGAAGCTTGAAGCTGTCGTCTATGTTGCTGGAGACAACCTCAGGAGCACTCTCCCTC"}
	//words := []string{"CGCGTCCGGTGCTAGCGACGTTCCGTTTTCTTTTATATGAAGACTGAAGTTATAGGCGATCGCTCCGATGGTGGTGCCACGCGTGTATTCTAATAGCTTCTTGAAGATCGTTGGGAGTAGCCATTGCAACTCATAGCAGCTGCAGAGACCCGTTTTTATAAAGGAAGATGGCTCTGGTTCTCGTCAGGTAGCGCAACCGGCGGACAGGACGGAGAAGCGGAGACGGGAGGGCTTTCTGATCAAGTTAGAGGGCACCGTACTCAAGGTTAGCTTTGCTGCTGAGTTCTGGCGCTCCTTTTTAGGGATTAGTTAGGTGATGTATTGCAGAGCCGTAACATCACTTATGGATGGCGAATCATGAGCATAAACCAGGGTCCATCGAGGCGAGGTGCGCTACATTCTACTGTGGAGACCAACTGGTCACTTCTTACAGTTAATGATTAAACCCAAGACCTAAATTGTCGCCACTTTCTGGCGGGCGGCATAGCTACATAATGACGGCTGAAAACCCCCAACGTGTGACTGTCATTATGATTACTGTGATTACTGGTATATCTATAGCCGTGCCACAACTTCACAGCACGGAGCGAGTCGGGTTACGTGGCAGCCCCGCGCCTCATCTATTAGGAGCCTGTACAGTTCACTGAGATCCCGATCAGTGGTACAAAGGTGAATGCTCTGCAATTTGCCCGCTGTTCTTCTGTTTACGATAGGCCGGGAAAAGTCAACCGCCCGCAGTAATTGTCACCCAGCGGGTAACAAGGACACGGACGGTCTGTTTGCCGGTTGGAAGTGATGGACGGCGGAATGCGATTCGTGTTGGTCCATATCTAGTAGCAAGGGTGTCACCAGCCGCTGGCTATTCCACATTAACCGGGTTAATATGTCTTATAGTAGCTCACCAAATTGCGACACGACAGGGTCGCTAAAGAGGGCTTGGAAATTCAATATGCTTGACACGTGGAATATGCCGCGAAGTAACCAATAACGTCACAACTGGTATACGGAGCCCGGTCACTTGCCCCCGCATCGGCGCGTCAGTGCGTGAAGGTAGATCGGAGCGCCCCTGGTACTCCATCGACCCTAGTACTCGCCCGGTTGCCCTCTTTCCCCAGAACGTCTGACCAGTACGGGCCCCAATGCTCTCGGGTATCTTGCGACAATGTATCCAACTTTTAAACTTATTGTACAAATACTGGAGAGTTACGACTCGACTGGCTAATCATCGTCGTTTCGTTTAAAAGCTACTAAAAACTTTGTATCACGAAGGTAGTATAGGACTAGGCCTGATCCCATGGCCGAAAATGAAGCATAGGCTTGGCAGCAACTTTTCATCGATTGTCTAATCATCGACGTTTGCCACATAGCTGTTGGGCAGTCCATAAGTCACTTTGCTGTCGCCAGTGGGCCGAATGGTGTTTTCTGCAATGAATCTCCACACGTGTTGTCCGATTGATTCCAGGGGGAGTATCCATAACACACCCACTTTTGACTCAAAACGACGACACCAGGCGGGCCGTTAGATAAATAAGGGGTACAGAGCAGGTCTCTCCTGTGTAGCTATGCGGATTTCCCGGTATCGACGCAACGTGTATTTACAGGTAACAACCCATGTCGTCTAGATCGGTAGACGACTGGGGGCATACAGGAATAACGGATTCCGATTGAAGATCTAGGAACCTGGTCCACGAATCATGCGGCGCAAAACTGCGCGCACAGATCCATTAAGCGGTATTAATATGTGTTCAGTGTATCCCTTAGAAGCAGTCAGAAGGTCCCCAATCATGATACCACTGTGAAGTTTTGGTTAGGACTCTCACCAGTCGAGTCGCCTCTAGATTCTAAATCAATCCTCTCATACTCACTGGAAATGAGTAGTAGTGCGCGAGACAATTGGACCAATGACTCTAGATGCCTTTGGGGTCGACAAAATCGTTAACCTAGGACGTAGCCAAGCACTCATTGTGTTATCGCCGGTGACTATGACGCAAGACTTCCCG"}

	tree := datastructure.CreateTree()

	for k, word := range words {
		fmt.Println(k, word)

		//for i := 0; i < len(word); i++ {
		//	fmt.Println(word[i])
		//}

		tree.AddSequence(word, k)
	}

	fmt.Println("edge list:")
	tree.ToEdgeList(false)

	//tree.PropagatePositionsToInnerNodes(tree.RootId)

	fmt.Println("positions:")
	tree.PrintNodes()

	//pattern := "BC"
	//fmt.Println("searching for pattern", pattern)
	//result := tree.FindPatternExact(&pattern)
	//
	//for _, match := range result.Matches {
	//	fmt.Println(match)
	//}

}
