package main

import (
	"fmt"
	"github.com/KleinSamuel/gtamap/src/core/datastructure"
	"github.com/sirupsen/logrus"
	"math/rand"
	"time"
)

func generateCombinations(chars []rune, prefix string, length int, words *[]string) {
	if length == 0 {
		*words = append(*words, prefix+"1")
		//return
	}

	for _, char := range chars {
		generateCombinations(chars, prefix+string(char), length-1, words)
	}
}

type Test struct {
	Active int
	Root   int
}

func createString() {
	rand.Seed(time.Now().UnixNano())
	length := 2000
	chars := []rune{'A', 'C', 'T', 'G'}
	randomString := make([]rune, length)

	for i := range randomString {
		randomString[i] = chars[rand.Intn(len(chars))]
	}

	fmt.Println(string(randomString))
}

func main() {

	logrus.SetFormatter(&logrus.TextFormatter{
		FullTimestamp: true,
	})
	logrus.SetLevel(logrus.InfoLevel)

	//alphabet := []rune{'A', 'T', 'G', 'C'}
	//for i := 1; i <= 10; i++ {
	//	words := make([]string, 0)
	//	generateCombinations(alphabet, "", i, &words)
	//
	//	for _, word := range words {
	//
	//		fmt.Println("checking word", word)
	//
	//		tree := datastructure.CreateTree()
	//		tree.AddSequence(word, 0)
	//	}
	//}
	//fmt.Println("OK")

	words := []string{"ATGC1", "ATGG2", "ATTTTG13"}
	//words := []string{"AATAT1"}
	//words := []string{"AATATAT1"}
	//words := []string{"ATGCGC1"}
	//words := []string{"ATGACACCCACAGACTTCACAAG1"}
	//words := []string{"ATGACACCCACAGACTTCACAAGCCCTATTCCTAACATGGCTGATGAC1"}
	//words := []string{"ATGACACCCACAGACTTCACAAGCCCTATTCCTAACATGGCTGATGACTATGGCTCTGAATCCACATCTTCCATGGAAGACTACGTTAACTTCAACTTCACTGACTTCTACTGTGAGAAAAACAATGTCAGGCAGTTTGCGAGCCATTTCCTCCCACCCTTGTACTGGCTCGTGTTCATCGTGGGTGCCTTGGGCAACAGTCTTGTTATCCTTGTCTACTGGTACTGCACAAGAGTGAAGACCATGACCGACATGTTCCTTTTGAATTTGGCAATTGCTGACCTCCTCTTTCTTGTCACTCTTCCCTTCTGGGCCATTGCTGCTGCTGACCAGTGGAAGTTCCAGACCTTCATGTGCAAGGTGGTCAACAGCATGTACAAGATGAACTTCTACAGCTGTGTGTTGCTGATCATGTGCATCAGCGTGGACAGGTACATTGCCATTGCCCAGGCCATGAGAGCACATACTTGGAGGGAGAAAAGGCTTTTGTACAGCAAAATGGTTTGCTTTACCATCTGGGTATTGGCAGCTGCTCTCTGCATCCCAGAAATCTTATACAGCCAAATCAAGGAGGAATCCGGCATTGCTATCTGCACCATGGTTTACCCTAGCGATGAGAGCACCAAACTGAAGTCAGCTGTCTTGACCCTGAAGGTCATTCTGGGGTTCTTCCTTCCCTTCGTGGTCATGGCTTGCTGCTATACCATCATCATTCACACCCTGATACAAGCCAAGAAGTCTTCCAAGCACAAAGCCCTAAAAGTGACCATCACTGTCCTGACCGTCTTTGTCTTGTCTCAGTTTCCCTACAACTGCATTTTGTTGGTGCAGACCATTGACGCCTATGCCATGTTCATCTCCAACTGTGCCGTTTCCACCAACATTGACATCTGCTTCCAGGTCACCCAGACCATCGCCTTCTTCCACAGTTGCCTGAACCCTGTTCTCTATGTTTTTGTGGGTGAGAGATTCCGCCGGGATCTCGTGAAAACCCTGAAGAACTTGGGTTGCATCAGCCAGGCCCAGTGGGTTTCATTTACAAGGAGAGAGGGAAGCTTGAAGCTGTCGTCTATGTTGCTGGAGACAACCTCAGGAGCACTCTCCCTC"}
	//words := []string{"CGCGTCCGGTGCTAGCGACGTTCCGTTTTCTTTTATATGAAGACTGAAGTTATAGGCGATCGCTCCGATGGTGGTGCCACGCGTGTATTCTAATAGCTTCTTGAAGATCGTTGGGAGTAGCCATTGCAACTCATAGCAGCTGCAGAGACCCGTTTTTATAAAGGAAGATGGCTCTGGTTCTCGTCAGGTAGCGCAACCGGCGGACAGGACGGAGAAGCGGAGACGGGAGGGCTTTCTGATCAAGTTAGAGGGCACCGTACTCAAGGTTAGCTTTGCTGCTGAGTTCTGGCGCTCCTTTTTAGGGATTAGTTAGGTGATGTATTGCAGAGCCGTAACATCACTTATGGATGGCGAATCATGAGCATAAACCAGGGTCCATCGAGGCGAGGTGCGCTACATTCTACTGTGGAGACCAACTGGTCACTTCTTACAGTTAATGATTAAACCCAAGACCTAAATTGTCGCCACTTTCTGGCGGGCGGCATAGCTACATAATGACGGCTGAAAACCCCCAACGTGTGACTGTCATTATGATTACTGTGATTACTGGTATATCTATAGCCGTGCCACAACTTCACAGCACGGAGCGAGTCGGGTTACGTGGCAGCCCCGCGCCTCATCTATTAGGAGCCTGTACAGTTCACTGAGATCCCGATCAGTGGTACAAAGGTGAATGCTCTGCAATTTGCCCGCTGTTCTTCTGTTTACGATAGGCCGGGAAAAGTCAACCGCCCGCAGTAATTGTCACCCAGCGGGTAACAAGGACACGGACGGTCTGTTTGCCGGTTGGAAGTGATGGACGGCGGAATGCGATTCGTGTTGGTCCATATCTAGTAGCAAGGGTGTCACCAGCCGCTGGCTATTCCACATTAACCGGGTTAATATGTCTTATAGTAGCTCACCAAATTGCGACACGACAGGGTCGCTAAAGAGGGCTTGGAAATTCAATATGCTTGACACGTGGAATATGCCGCGAAGTAACCAATAACGTCACAACTGGTATACGGAGCCCGGTCACTTGCCCCCGCATCGGCGCGTCAGTGCGTGAAGGTAGATCGGAGCGCCCCTGGTACTCCATCGACCCTAGTACTCGCCCGGTTGCCCTCTTTCCCCAGAACGTCTGACCAGTACGGGCCCCAATGCTCTCGGGTATCTTGCGACAATGTATCCAACTTTTAAACTTATTGTACAAATACTGGAGAGTTACGACTCGACTGGCTAATCATCGTCGTTTCGTTTAAAAGCTACTAAAAACTTTGTATCACGAAGGTAGTATAGGACTAGGCCTGATCCCATGGCCGAAAATGAAGCATAGGCTTGGCAGCAACTTTTCATCGATTGTCTAATCATCGACGTTTGCCACATAGCTGTTGGGCAGTCCATAAGTCACTTTGCTGTCGCCAGTGGGCCGAATGGTGTTTTCTGCAATGAATCTCCACACGTGTTGTCCGATTGATTCCAGGGGGAGTATCCATAACACACCCACTTTTGACTCAAAACGACGACACCAGGCGGGCCGTTAGATAAATAAGGGGTACAGAGCAGGTCTCTCCTGTGTAGCTATGCGGATTTCCCGGTATCGACGCAACGTGTATTTACAGGTAACAACCCATGTCGTCTAGATCGGTAGACGACTGGGGGCATACAGGAATAACGGATTCCGATTGAAGATCTAGGAACCTGGTCCACGAATCATGCGGCGCAAAACTGCGCGCACAGATCCATTAAGCGGTATTAATATGTGTTCAGTGTATCCCTTAGAAGCAGTCAGAAGGTCCCCAATCATGATACCACTGTGAAGTTTTGGTTAGGACTCTCACCAGTCGAGTCGCCTCTAGATTCTAAATCAATCCTCTCATACTCACTGGAAATGAGTAGTAGTGCGCGAGACAATTGGACCAATGACTCTAGATGCCTTTGGGGTCGACAAAATCGTTAACCTAGGACGTAGCCAAGCACTCATTGTGTTATCGCCGGTGACTATGACGCAAGACTTCCCG"}

	tree := datastructure.CreateTree()

	for k, word := range words {
		tree.AddSequence(word, k)
	}

	//tree.ToEdgeList(false)
	//tree.PrintNodes()

	result := tree.FindPatternExact("G")

	for _, match := range result.Matches {
		fmt.Println(match)
	}

}
